name: Amrat PC Remote Control
on: workflow_dispatch

jobs:
  launch_remote:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install playwright requests telebot

      - name: Run Remote PC Check
        run: |
          python spoofer.py
