name: Amrat Multi Process Grid
on: workflow_dispatch

jobs:
  launch_grid:
    runs-on: ubuntu-latest  # यह गिटहब का खुद का कंप्यूटर यूज़ करेगा
    strategy:
      matrix:
        machine_id: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install playwright requests telebot
          playwright install firefox
          playwright install-deps firefox

      - name: Run Check Flow
        run: |
          python spoofer.py "${{ matrix.machine_id }}"
